version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: bankingportal-app
    ports:
      - "8180:8180"
    depends_on:
      - mysql
      - redis
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bankingapp
      SPRING_DATASOURCE_USERNAME: bankinguser
      SPRING_DATASOURCE_PASSWORD: bankingpass

      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - banking-network

  mysql:
    image: mysql:8.0
    container_name: bankingportal-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bankingapp
      MYSQL_USER: bankinguser
      MYSQL_PASSWORD: bankingpass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - banking-network

  redis:
    image: redis:7-alpine
    container_name: bankingportal-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    command: redis-server --appendonly yes
    networks:
      - banking-network

  kafka:
    image: apache/kafka:3.7.0
    container_name: bankingportal-kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093

      # 🔥 FIXED HERE
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - ./kafka/data:/var/lib/kafka/data
    networks:
      - banking-network

networks:
  banking-network:
    driver: bridge
